import { v4 as uuidv4 } from 'uuid';
import { STORAGE_KEYS, setItem, getItem } from './storage';
import type {
  User,
  Company,
  BatteryProduct,
  InverterProduct,
  Manufacturer,
  Quote,
  CommissioningSubmission,
} from '../types';

export function initializeSeedData(): void {
  // Check if already initialized
  if (getItem<boolean>(STORAGE_KEYS.INITIALIZED)) {
    return;
  }

  // Seed Manufacturers
  const manufacturers: Manufacturer[] = [
    {
      id: 'mfr-tesla',
      name: 'Tesla',
      logo: 'https://logo.clearbit.com/tesla.com',
      website: 'https://www.tesla.com',
      supportEmail: 'support@tesla.com',
      isActive: true,
    },
    {
      id: 'mfr-givenergy',
      name: 'GivEnergy',
      logo: 'https://logo.clearbit.com/givenergy.co.uk',
      website: 'https://www.givenergy.co.uk',
      supportEmail: 'support@givenergy.co.uk',
      isActive: true,
    },
    {
      id: 'mfr-solax',
      name: 'SolaX',
      logo: 'https://logo.clearbit.com/solaxpower.com',
      website: 'https://www.solaxpower.com',
      supportEmail: 'support@solaxpower.com',
      isActive: true,
    },
    {
      id: 'mfr-foxess',
      name: 'Fox ESS',
      logo: 'https://logo.clearbit.com/fox-ess.com',
      website: 'https://www.fox-ess.com',
      supportEmail: 'support@fox-ess.com',
      isActive: true,
    },
    {
      id: 'mfr-huawei',
      name: 'Huawei',
      logo: 'https://logo.clearbit.com/huawei.com',
      website: 'https://www.huawei.com',
      supportEmail: 'support@huawei.com',
      isActive: true,
    },
  ];

  // Seed Battery Products
  const batteries: BatteryProduct[] = [
    {
      id: 'bat-tesla-pw2',
      manufacturerId: 'mfr-tesla',
      manufacturerName: 'Tesla',
      model: 'Powerwall 2',
      capacityKwh: 13.5,
      powerKw: 5,
      chemistry: 'Lithium-ion NMC',
      warrantyYears: 10,
      cycleLife: 4000,
      efficiency: 90,
      dimensions: '1150 x 755 x 155 mm',
      weight: 114,
      costPrice: 6500,
      rrp: 8500,
      isActive: true,
    },
    {
      id: 'bat-tesla-pw3',
      manufacturerId: 'mfr-tesla',
      manufacturerName: 'Tesla',
      model: 'Powerwall 3',
      capacityKwh: 13.5,
      powerKw: 11.5,
      chemistry: 'Lithium-ion NMC',
      warrantyYears: 10,
      cycleLife: 4000,
      efficiency: 97.5,
      dimensions: '1098 x 609 x 193 mm',
      weight: 130,
      costPrice: 7200,
      rrp: 9500,
      isActive: true,
    },
    {
      id: 'bat-ge-5.2',
      manufacturerId: 'mfr-givenergy',
      manufacturerName: 'GivEnergy',
      model: 'All-in-One 5.2kWh',
      capacityKwh: 5.2,
      powerKw: 3,
      chemistry: 'LiFePO4',
      warrantyYears: 12,
      cycleLife: 6000,
      efficiency: 95,
      dimensions: '980 x 580 x 200 mm',
      weight: 75,
      costPrice: 2800,
      rrp: 3800,
      isActive: true,
    },
    {
      id: 'bat-ge-9.5',
      manufacturerId: 'mfr-givenergy',
      manufacturerName: 'GivEnergy',
      model: 'All-in-One 9.5kWh',
      capacityKwh: 9.5,
      powerKw: 3.6,
      chemistry: 'LiFePO4',
      warrantyYears: 12,
      cycleLife: 6000,
      efficiency: 95,
      dimensions: '1220 x 580 x 200 mm',
      weight: 112,
      costPrice: 4200,
      rrp: 5600,
      isActive: true,
    },
    {
      id: 'bat-solax-5.8',
      manufacturerId: 'mfr-solax',
      manufacturerName: 'SolaX',
      model: 'Triple Power T58',
      capacityKwh: 5.8,
      powerKw: 3,
      chemistry: 'LiFePO4',
      warrantyYears: 10,
      cycleLife: 6000,
      efficiency: 95,
      dimensions: '670 x 480 x 226 mm',
      weight: 65,
      costPrice: 2400,
      rrp: 3200,
      isActive: true,
    },
    {
      id: 'bat-fox-5.76',
      manufacturerId: 'mfr-foxess',
      manufacturerName: 'Fox ESS',
      model: 'ECS2900-H5',
      capacityKwh: 5.76,
      powerKw: 2.9,
      chemistry: 'LiFePO4',
      warrantyYears: 10,
      cycleLife: 6000,
      efficiency: 95,
      dimensions: '600 x 580 x 200 mm',
      weight: 54,
      costPrice: 2200,
      rrp: 2900,
      isActive: true,
    },
    {
      id: 'bat-huawei-5',
      manufacturerId: 'mfr-huawei',
      manufacturerName: 'Huawei',
      model: 'LUNA2000-5-S0',
      capacityKwh: 5,
      powerKw: 2.5,
      chemistry: 'LiFePO4',
      warrantyYears: 10,
      cycleLife: 4000,
      efficiency: 95,
      dimensions: '670 x 600 x 150 mm',
      weight: 63.8,
      costPrice: 2600,
      rrp: 3400,
      isActive: true,
    },
    {
      id: 'bat-huawei-10',
      manufacturerId: 'mfr-huawei',
      manufacturerName: 'Huawei',
      model: 'LUNA2000-10-S0',
      capacityKwh: 10,
      powerKw: 5,
      chemistry: 'LiFePO4',
      warrantyYears: 10,
      cycleLife: 4000,
      efficiency: 95,
      dimensions: '670 x 600 x 300 mm',
      weight: 114,
      costPrice: 4600,
      rrp: 6000,
      isActive: true,
    },
  ];

  // Seed Inverter Products
  const inverters: InverterProduct[] = [
    {
      id: 'inv-ge-3.6',
      manufacturerId: 'mfr-givenergy',
      manufacturerName: 'GivEnergy',
      model: 'Gen 3 3.6kW Hybrid',
      powerKw: 3.6,
      phases: 1,
      efficiency: 97.6,
      warrantyYears: 12,
      costPrice: 1200,
      rrp: 1600,
      features: ['EPS', 'Smart Export', 'App Control', 'G99 Ready'],
      isActive: true,
    },
    {
      id: 'inv-ge-5',
      manufacturerId: 'mfr-givenergy',
      manufacturerName: 'GivEnergy',
      model: 'Gen 3 5kW Hybrid',
      powerKw: 5,
      phases: 1,
      efficiency: 97.6,
      warrantyYears: 12,
      costPrice: 1400,
      rrp: 1850,
      features: ['EPS', 'Smart Export', 'App Control', 'G99 Ready'],
      isActive: true,
    },
    {
      id: 'inv-solax-3.7',
      manufacturerId: 'mfr-solax',
      manufacturerName: 'SolaX',
      model: 'X1-Hybrid G4 3.7kW',
      powerKw: 3.7,
      phases: 1,
      efficiency: 97.8,
      warrantyYears: 10,
      costPrice: 1100,
      rrp: 1450,
      features: ['EPS', 'G99 Ready', 'Smart Meter Compatible'],
      isActive: true,
    },
    {
      id: 'inv-fox-5',
      manufacturerId: 'mfr-foxess',
      manufacturerName: 'Fox ESS',
      model: 'H1-5.0-E',
      powerKw: 5,
      phases: 1,
      efficiency: 97.5,
      warrantyYears: 10,
      costPrice: 1150,
      rrp: 1500,
      features: ['EPS', 'G99 Ready', 'CT Clamp Included'],
      isActive: true,
    },
    {
      id: 'inv-huawei-5',
      manufacturerId: 'mfr-huawei',
      manufacturerName: 'Huawei',
      model: 'SUN2000-5KTL-M1',
      powerKw: 5,
      phases: 1,
      efficiency: 98.6,
      warrantyYears: 10,
      costPrice: 1000,
      rrp: 1350,
      features: ['AI Optimization', 'FusionSolar App', 'G99 Ready'],
      isActive: true,
    },
  ];

  // Seed Companies
  const companies: Company[] = [
    {
      id: 'comp-admin',
      name: 'Logi6 Platform',
      email: 'admin@log6.co.uk',
      phone: '020 7123 4567',
      address: '1 Platform Way',
      postcode: 'EC1A 1BB',
      isUmbrellaScheme: false,
      subscriptionTier: 'enterprise',
      subscriptionStatus: 'active',
      subscriptionEndDate: '2025-12-31',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'comp-solar-solutions',
      name: 'Solar Solutions UK',
      email: 'info@solarsolutions.co.uk',
      phone: '0117 456 7890',
      address: '45 Green Lane',
      postcode: 'BS1 4AB',
      mcsNumber: 'MCS/12345',
      isUmbrellaScheme: false,
      subscriptionTier: 'professional',
      subscriptionStatus: 'active',
      subscriptionEndDate: '2025-06-30',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'comp-energy-first',
      name: 'Energy First Installations',
      email: 'contact@energyfirst.co.uk',
      phone: '0161 789 0123',
      address: '78 Renewable Road',
      postcode: 'M1 2BC',
      isUmbrellaScheme: true,
      subscriptionTier: 'starter',
      subscriptionStatus: 'trial',
      subscriptionEndDate: '2025-01-15',
      createdAt: new Date().toISOString(),
    },
  ];

  // Seed Users
  const users: User[] = [
    {
      id: 'user-admin',
      email: 'admin@log6.co.uk',
      name: 'Platform Admin',
      role: 'admin',
      companyId: 'comp-admin',
      companyName: 'Logi6 Platform',
      createdAt: new Date().toISOString(),
      lastLogin: new Date().toISOString(),
      isActive: true,
    },
    {
      id: 'user-installer',
      email: 'installer@solarsolutions.co.uk',
      name: 'James Wilson',
      role: 'installer',
      companyId: 'comp-solar-solutions',
      companyName: 'Solar Solutions UK',
      createdAt: new Date().toISOString(),
      lastLogin: new Date().toISOString(),
      isActive: true,
    },
    {
      id: 'user-installer-2',
      email: 'tech@energyfirst.co.uk',
      name: 'Sarah Thompson',
      role: 'installer',
      companyId: 'comp-energy-first',
      companyName: 'Energy First Installations',
      createdAt: new Date().toISOString(),
      lastLogin: new Date().toISOString(),
      isActive: true,
    },
    {
      id: 'user-assessor',
      email: 'assessor@log6.co.uk',
      name: 'Michael Brown',
      role: 'assessor',
      companyId: 'comp-admin',
      companyName: 'Logi6 Platform',
      createdAt: new Date().toISOString(),
      lastLogin: new Date().toISOString(),
      isActive: true,
    },
  ];

  // Seed Sample Quotes
  const quotes: Quote[] = [
    {
      id: 'quote-001',
      companyId: 'comp-solar-solutions',
      installerId: 'user-installer',
      installerName: 'James Wilson',
      reference: 'QT-2024-001',
      status: 'sent',
      installationType: 'residential',
      customer: {
        name: 'John Smith',
        email: 'john.smith@email.com',
        phone: '07700 900123',
        address: '123 Oak Avenue, Bristol',
        postcode: 'BS5 7JK',
        propertyType: 'house',
        existingSolar: true,
        solarCapacityKwp: 4.5,
        annualConsumptionKwh: 4200,
        currentTariff: 'Standard Variable',
        hasEv: true,
        evMileagePerYear: 8000,
      },
      tariff: {
        importRate: 0.285,
        exportRate: 0.15,
        standingCharge: 0.55,
        hasTimeOfUse: true,
        peakRate: 0.38,
        offPeakRate: 0.12,
        peakHoursStart: '16:00',
        peakHoursEnd: '19:00',
      },
      lineItems: [
        {
          id: 'li-1',
          type: 'battery',
          productId: 'bat-ge-9.5',
          description: 'GivEnergy All-in-One 9.5kWh Battery',
          quantity: 1,
          unitPrice: 5600,
          costPrice: 4200,
        },
        {
          id: 'li-2',
          type: 'inverter',
          productId: 'inv-ge-5',
          description: 'GivEnergy Gen 3 5kW Hybrid Inverter',
          quantity: 1,
          unitPrice: 1850,
          costPrice: 1400,
        },
        {
          id: 'li-3',
          type: 'installation',
          description: 'Professional Installation & Commissioning',
          quantity: 1,
          unitPrice: 1500,
          costPrice: 800,
        },
        {
          id: 'li-4',
          type: 'other',
          description: 'DNO Application & G99 Registration',
          quantity: 1,
          unitPrice: 250,
          costPrice: 150,
        },
      ],
      subtotal: 9200,
      vatRate: 0,
      vatAmount: 0,
      total: 9200,
      deposit: 2000,
      margin: 2600,
      marginPercentage: 28.3,
      roiProjections: Array.from({ length: 10 }, (_, i) => ({
        year: i + 1,
        savings: 850 + i * 50,
        cumulativeSavings: (850 + i * 50) * (i + 1),
        evTaxSavings: 180,
        exportRevenue: 320,
        loadShiftSavings: 350 + i * 25,
      })),
      paybackYears: 7.2,
      annualSavings: 1350,
      notes: 'Customer interested in backup power capability. Recommended EPS setup.',
      validUntil: '2025-01-15',
      createdAt: '2024-12-01T10:00:00Z',
      updatedAt: '2024-12-05T14:30:00Z',
      sentAt: '2024-12-05T14:30:00Z',
    },
    {
      id: 'quote-002',
      companyId: 'comp-solar-solutions',
      installerId: 'user-installer',
      installerName: 'James Wilson',
      reference: 'QT-2024-002',
      status: 'accepted',
      installationType: 'residential',
      customer: {
        name: 'Emma Davies',
        email: 'emma.davies@email.com',
        phone: '07700 900456',
        address: '45 Willow Gardens, Bath',
        postcode: 'BA2 4RT',
        propertyType: 'house',
        existingSolar: true,
        solarCapacityKwp: 6,
        annualConsumptionKwh: 5500,
        currentTariff: 'Octopus Go',
        hasEv: true,
        evMileagePerYear: 12000,
      },
      tariff: {
        importRate: 0.25,
        exportRate: 0.15,
        standingCharge: 0.48,
        hasTimeOfUse: true,
        peakRate: 0.25,
        offPeakRate: 0.075,
        peakHoursStart: '05:30',
        peakHoursEnd: '23:30',
      },
      lineItems: [
        {
          id: 'li-5',
          type: 'battery',
          productId: 'bat-tesla-pw3',
          description: 'Tesla Powerwall 3 13.5kWh',
          quantity: 1,
          unitPrice: 9500,
          costPrice: 7200,
        },
        {
          id: 'li-6',
          type: 'installation',
          description: 'Tesla Certified Installation',
          quantity: 1,
          unitPrice: 1800,
          costPrice: 1000,
        },
        {
          id: 'li-7',
          type: 'other',
          description: 'Gateway & Monitoring Setup',
          quantity: 1,
          unitPrice: 350,
          costPrice: 200,
        },
      ],
      subtotal: 11650,
      vatRate: 0,
      vatAmount: 0,
      total: 11650,
      deposit: 3000,
      margin: 3250,
      marginPercentage: 27.9,
      roiProjections: Array.from({ length: 10 }, (_, i) => ({
        year: i + 1,
        savings: 1100 + i * 60,
        cumulativeSavings: (1100 + i * 60) * (i + 1),
        evTaxSavings: 280,
        exportRevenue: 420,
        loadShiftSavings: 400 + i * 30,
      })),
      paybackYears: 6.5,
      annualSavings: 1800,
      notes: 'Premium installation with full home backup capability.',
      validUntil: '2025-01-10',
      createdAt: '2024-11-20T09:00:00Z',
      updatedAt: '2024-11-28T16:00:00Z',
      sentAt: '2024-11-22T10:00:00Z',
      viewedAt: '2024-11-22T14:30:00Z',
      acceptedAt: '2024-11-28T16:00:00Z',
      customerSignature: 'Emma Davies',
    },
    {
      id: 'quote-003',
      companyId: 'comp-energy-first',
      installerId: 'user-installer-2',
      installerName: 'Sarah Thompson',
      reference: 'QT-2024-003',
      status: 'draft',
      installationType: 'residential',
      customer: {
        name: 'David Brown',
        email: 'david.brown@email.com',
        phone: '07700 900789',
        address: '78 Maple Close, Manchester',
        postcode: 'M20 5GH',
        propertyType: 'house',
        existingSolar: false,
        annualConsumptionKwh: 3800,
        currentTariff: 'British Gas Fixed',
        hasEv: false,
      },
      tariff: {
        importRate: 0.30,
        exportRate: 0.15,
        standingCharge: 0.52,
        hasTimeOfUse: false,
      },
      lineItems: [
        {
          id: 'li-8',
          type: 'battery',
          productId: 'bat-fox-5.76',
          description: 'Fox ESS ECS2900-H5 5.76kWh',
          quantity: 1,
          unitPrice: 2900,
          costPrice: 2200,
        },
        {
          id: 'li-9',
          type: 'inverter',
          productId: 'inv-fox-5',
          description: 'Fox ESS H1-5.0-E Hybrid Inverter',
          quantity: 1,
          unitPrice: 1500,
          costPrice: 1150,
        },
        {
          id: 'li-10',
          type: 'installation',
          description: 'Installation & Setup',
          quantity: 1,
          unitPrice: 1200,
          costPrice: 700,
        },
      ],
      subtotal: 5600,
      vatRate: 0,
      vatAmount: 0,
      total: 5600,
      deposit: 1500,
      margin: 1550,
      marginPercentage: 27.7,
      roiProjections: Array.from({ length: 10 }, (_, i) => ({
        year: i + 1,
        savings: 520 + i * 30,
        cumulativeSavings: (520 + i * 30) * (i + 1),
        evTaxSavings: 0,
        exportRevenue: 180,
        loadShiftSavings: 340 + i * 20,
      })),
      paybackYears: 8.5,
      annualSavings: 700,
      notes: 'Budget-conscious customer. Recommended starting point for battery storage.',
      validUntil: '2025-01-20',
      createdAt: '2024-12-08T11:00:00Z',
      updatedAt: '2024-12-08T11:00:00Z',
    },
  ];

  // Seed Sample Commissioning Submissions
  const commissions: CommissioningSubmission[] = [
    {
      id: 'comm-001',
      quoteId: 'quote-002',
      installerId: 'user-installer',
      installerName: 'James Wilson',
      companyId: 'comp-solar-solutions',
      companyName: 'Solar Solutions UK',
      status: 'pending_review',
      systemDetails: {
        batteryModel: 'Tesla Powerwall 3',
        inverterModel: 'Integrated',
        capacityKwh: 13.5,
        installationDate: '2024-12-05',
      },
      siteDetails: {
        customerName: 'Emma Davies',
        address: '45 Willow Gardens, Bath',
        postcode: 'BA2 4RT',
      },
      checklist: {
        visualInspection: true,
        cablingCompliant: true,
        labelingComplete: true,
        isolationDevices: true,
        earthingVerified: true,
        testingComplete: true,
        customerBriefed: true,
        documentationProvided: true,
      },
      photos: [
        {
          id: 'photo-1',
          type: 'battery',
          url: '/placeholder-battery.jpg',
          caption: 'Powerwall 3 mounted on garage wall',
          uploadedAt: '2024-12-06T10:00:00Z',
        },
        {
          id: 'photo-2',
          type: 'meter',
          url: '/placeholder-meter.jpg',
          caption: 'CT clamp installation on meter tails',
          uploadedAt: '2024-12-06T10:05:00Z',
        },
      ],
      notes: 'Clean installation completed. Customer very happy with the system.',
      submittedAt: '2024-12-06T10:30:00Z',
      createdAt: '2024-12-06T10:30:00Z',
      updatedAt: '2024-12-06T10:30:00Z',
    },
  ];

  // Save all seed data
  setItem(STORAGE_KEYS.MANUFACTURERS, manufacturers);
  setItem(STORAGE_KEYS.PRODUCTS_BATTERIES, batteries);
  setItem(STORAGE_KEYS.PRODUCTS_INVERTERS, inverters);
  setItem(STORAGE_KEYS.COMPANIES, companies);
  setItem(STORAGE_KEYS.USERS, users);
  setItem(STORAGE_KEYS.QUOTES, quotes);
  setItem(STORAGE_KEYS.COMMISSIONS, commissions);
  setItem(STORAGE_KEYS.MIS_DOCUMENTS, []);
  setItem(STORAGE_KEYS.CERTIFICATES, []);
  setItem(STORAGE_KEYS.NOTIFICATIONS, []);
  setItem(STORAGE_KEYS.INITIALIZED, true);

  console.log('Seed data initialized successfully');
}

